-record(post, {id, title, date, keywords, body}).
-record(comment, 
	{id="",
	 post_id="",
	 date,
	 ip="0.0.0.0",
	 user_agent,
	 referrer,
	 type="comment",
	 author,
	 email="",
	 title="",
	 body,
	 rating=spam,
	 confirmed=false}).
